---
# Simple CloudSigma Cluster Example
# A minimal cluster with 2 CloudSigma worker nodes
#
# Prerequisites:
#   - CloudSigma credentials configured
#   - Base cluster with CAPI installed
#   - cluster-api-provider-cloudsigma deployed
#
# Usage:
#   kubectl apply -f cloudsigma-cluster-simple.yaml

---
# CloudSigmaMachineTemplate defines the VM specification
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CloudSigmaMachineTemplate
metadata:
  name: cloudsigma-cluster-workers
  namespace: default
spec:
  template:
    spec:
      cpu: 2000          # 2 GHz CPU
      memory: 4096       # 4 GB RAM
      disks:
        - uuid: "4afeb48e-3b2c-4f7e-ac8b-d9915ad69a79"  # Ubuntu 24.04 + K8s 1.34.1 + auto-bootstrap
          device: "virtio"
          boot_order: 1
          size: 10737418240  # 10 GB
      # No VLAN specified = auto-assign public NAT IP
      tags:
        - kubernetes
        - cloudsigma
        - worker
      meta:
        cluster: "cloudsigma-cluster"
        provider: "cloudsigma"

---
# KubeadmConfigTemplate for bootstrap configuration
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: cloudsigma-cluster-workers
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: "{{ ds.meta_data.local_hostname }}"
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: "cloudsigma://{{ ds.meta_data.instance_id }}"

---
# MachineDeployment creates and manages worker nodes
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: cloudsigma-cluster-workers
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: cloudsigma-cluster
spec:
  clusterName: cloudsigma-cluster
  replicas: 2  # 2 worker nodes
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cloudsigma-cluster
      cluster.x-k8s.io/deployment-name: cloudsigma-cluster-workers
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: cloudsigma-cluster
        cluster.x-k8s.io/deployment-name: cloudsigma-cluster-workers
        node-type: cloudsigma-worker
    spec:
      clusterName: cloudsigma-cluster
      version: v1.34.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: cloudsigma-cluster-workers
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: CloudSigmaMachineTemplate
        name: cloudsigma-cluster-workers
